# Learning

In [26]:
import numpy as np
import pandas as pd

In [28]:
X_raw = np.array([[500, 1], [1000, 2], [1500, 2], [2000, 3], 
                 [2500, 3], [3000, 4], [4000, 4], [5000, 5]], dtype=float)
y = np.array([150, 200, 250, 300,
              320, 380, 450, 550], dtype=float)

In [30]:
X_raw

array([[5.0e+02, 1.0e+00],
       [1.0e+03, 2.0e+00],
       [1.5e+03, 2.0e+00],
       [2.0e+03, 3.0e+00],
       [2.5e+03, 3.0e+00],
       [3.0e+03, 4.0e+00],
       [4.0e+03, 4.0e+00],
       [5.0e+03, 5.0e+00]])

In [31]:
np.zeros(X_raw.shape[1])

array([0., 0.])

In [32]:
y = y.reshape(-1, 1)
y

array([[150.],
       [200.],
       [250.],
       [300.],
       [320.],
       [380.],
       [450.],
       [550.]])

In [33]:
def train(X, y, lr=0.0001, epochs=200):
    W = np.zeros((X.shape[1], 1))
    b = np.zeros((1, 1))
    losses = []
    for _ in range(epochs + 1):
        pred = X @ W + b
        err  = pred - y
        loss = (err**2).mean()
        losses.append(loss)
        W -= lr * (2/len(y)) * X.T @ err
        b -= lr * (2/len(y)) * err.mean()
        if _ % 50 == 0:
            print(f"Without norm — epoch {_}: {loss}")
    return losses

In [37]:
X_no_norm = X_raw.res
losses_raw = train(X_no_norm, y, lr=0.000000001)
print(f"Without norm — epoch 0: {losses_raw[0]:.0f}, epoch 200: {losses_raw[-1]:.0f}")

Without norm — epoch 0: 120850.0
Without norm — epoch 50: 26944.316055119423
Without norm — epoch 100: 8109.594244562246
Without norm — epoch 150: 4331.902174176907
Without norm — epoch 200: 3574.2079584981843
Without norm — epoch 0: 120850, epoch 200: 3574


In [43]:
X_norm = (X_raw - X_raw.mean(axis=0))/ (X_raw.std(axis=0))
losses_raw = train(X_norm, y, lr = 0.18)

Without norm — epoch 0: 120850.0
Without norm — epoch 50: 1130.8984451035008
Without norm — epoch 100: 60.39752519925045
Without norm — epoch 150: 42.47364582813208
Without norm — epoch 200: 40.05662590455915


In [44]:
losses_raw

[np.float64(120850.0),
 np.float64(97763.26640534683),
 np.float64(88112.8790286417),
 np.float64(80281.35248231667),
 np.float64(73221.14500706994),
 np.float64(66788.91913623203),
 np.float64(60923.01188203205),
 np.float64(55573.05889403245),
 np.float64(50693.626119441455),
 np.float64(46243.318975023794),
 np.float64(42184.38810144244),
 np.float64(38482.4053701686),
 np.float64(35105.97141876639),
 np.float64(32026.44917300641),
 np.float64(29217.720834213604),
 np.float64(26655.966247475124),
 np.float64(24319.460768025452),
 np.float64(22188.39091031233),
 np.float64(20244.68621530107),
 np.float64(18471.865909217177),
 np.float64(16854.899052451496),
 np.float64(15380.076991831465),
 np.float64(14034.897033870702),
 np.float64(12807.956351832123),
 np.float64(11688.855226285508),
 np.float64(10668.108798046236),
 np.float64(9737.066584618979),
 np.float64(8887.83907715285),
 np.float64(8113.230795000628),
 np.float64(7406.6792297750235),
 np.float64(6762.199160774098),
 np.flo

In [46]:
X_no_norm.shape

(8, 2)

In [47]:
y.shape

(8, 1)

In [48]:
X_raw = X_raw.reshape(-1, 2)
X_raw

array([[5.0e+02, 1.0e+00],
       [1.0e+03, 2.0e+00],
       [1.5e+03, 2.0e+00],
       [2.0e+03, 3.0e+00],
       [2.5e+03, 3.0e+00],
       [3.0e+03, 4.0e+00],
       [4.0e+03, 4.0e+00],
       [5.0e+03, 5.0e+00]])

In [49]:
W = np.zeros((X_raw.shape[1], 1))
b = np.zeros((1, 1))

In [50]:
W

array([[0.],
       [0.]])

In [65]:
b

array([[0.]])

In [66]:
pred = X_raw @ W + b
pred

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [67]:
err = pred - y
err

array([[-150., -200., -250., -300., -320., -380., -450., -550.],
       [-150., -200., -250., -300., -320., -380., -450., -550.],
       [-150., -200., -250., -300., -320., -380., -450., -550.],
       [-150., -200., -250., -300., -320., -380., -450., -550.],
       [-150., -200., -250., -300., -320., -380., -450., -550.],
       [-150., -200., -250., -300., -320., -380., -450., -550.],
       [-150., -200., -250., -300., -320., -380., -450., -550.],
       [-150., -200., -250., -300., -320., -380., -450., -550.]])

In [68]:
loss = (err ** 2).mean()
loss

np.float64(120850.0)

In [69]:
losses = []

In [70]:
losses.append(loss)
losses

[np.float64(120850.0)]

In [71]:
W -= 0.00011 * (2/len(y)) * X_raw.T @ err
W

ValueError: non-broadcastable output operand with shape (2,1) doesn't match the broadcast shape (2,8)

In [33]:
-12.5 * 2/3

-8.333333333333334

# Practise

In [95]:
import numpy as np