In [1]:
import numpy as np
import pandas as pd

## Problem

In [3]:
data = {
    "SqFt": [2347, 1202, 3850, 920, 1750, 2100, 3100, 1450, 2800, 1150],
    "Age": [12, 45, 2, 80, 25, 10, 5, 30, 15, 60],
    "Bedrooms": [4, 2, 5, 1, 3, 3, 4, 2, 4, 2],
    "Dist_City": [3.2, 15.1, 0.8, 18.5, 7.4, 4.2, 2.1, 12.3, 5.5, 20.0],
    "Transit": [1, 0, 1, 0, 1, 1, 1, 0, 1, 0],
    "Luxury": [8, 3, 10, 2, 5, 7, 9, 4, 8, 1],
    "Price_k": [485.4, 185.2, 720.5, 110.8, 315.6, 410.2, 595.3, 240.7, 510.9, 130.4]
}

### Alternate way to prepare X

In [4]:
X = np.column_stack([data['SqFt'], data['Age']]).astype(float)
X

array([[2.347e+03, 1.200e+01],
       [1.202e+03, 4.500e+01],
       [3.850e+03, 2.000e+00],
       [9.200e+02, 8.000e+01],
       [1.750e+03, 2.500e+01],
       [2.100e+03, 1.000e+01],
       [3.100e+03, 5.000e+00],
       [1.450e+03, 3.000e+01],
       [2.800e+03, 1.500e+01],
       [1.150e+03, 6.000e+01]])

### Python way too - Preferable for no personal valid reason

In [5]:
X = np.array(list(zip(data['SqFt'], data['Age'], data['Bedrooms'], data['Dist_City'], data['Transit'], data['Luxury'])), dtype=float)
y = np.array(data['Price_k'], dtype=float).reshape(-1, 1)

In [47]:
df = pd.read_csv("../Real_estate.csv")

# df.iloc[:, :-1].to_numpy()
X = df.iloc[:, :-1].to_numpy()
y = df.iloc[:, -1].to_numpy().reshape(-1, 1)
X, y

(array([[1.0000000e+00, 2.0129170e+03, 3.2000000e+01, ..., 1.0000000e+01,
         2.4982980e+01, 1.2154024e+02],
        [2.0000000e+00, 2.0129170e+03, 1.9500000e+01, ..., 9.0000000e+00,
         2.4980340e+01, 1.2153951e+02],
        [3.0000000e+00, 2.0135830e+03, 1.3300000e+01, ..., 5.0000000e+00,
         2.4987460e+01, 1.2154391e+02],
        ...,
        [4.1200000e+02, 2.0132500e+03, 1.8800000e+01, ..., 7.0000000e+00,
         2.4979230e+01, 1.2153986e+02],
        [4.1300000e+02, 2.0130000e+03, 8.1000000e+00, ..., 5.0000000e+00,
         2.4966740e+01, 1.2154067e+02],
        [4.1400000e+02, 2.0135000e+03, 6.5000000e+00, ..., 9.0000000e+00,
         2.4974330e+01, 1.2154310e+02]], shape=(414, 7)),
 array([[ 37.9],
        [ 42.2],
        [ 47.3],
        [ 54.8],
        [ 43.1],
        [ 32.1],
        [ 40.3],
        [ 46.7],
        [ 18.8],
        [ 22.1],
        [ 41.4],
        [ 58.1],
        [ 39.3],
        [ 23.8],
        [ 34.3],
        [ 50.5],
        [ 70.

In [56]:
X, y

(array([[-1.72787213, -0.8236832 ,  1.25562831, ...,  2.00740741,
          1.12542985,  0.44876222],
        [-1.71950471, -0.8236832 ,  0.15708621, ...,  1.66750284,
          0.91244417,  0.40113894],
        [-1.71113729,  1.5411511 , -0.38779067, ...,  0.30788457,
          1.4868601 ,  0.68818338],
        ...,
        [ 1.71113729,  0.35873395,  0.09556786, ...,  0.98769371,
          0.82289337,  0.42397202],
        [ 1.71950471, -0.52896661, -0.84478418, ...,  0.30788457,
         -0.18475479,  0.47681429],
        [ 1.72787213,  1.24643451, -0.98539757, ...,  1.66750284,
          0.42757904,  0.63534111]], shape=(414, 7)),
 array([[ 37.9],
        [ 42.2],
        [ 47.3],
        [ 54.8],
        [ 43.1],
        [ 32.1],
        [ 40.3],
        [ 46.7],
        [ 18.8],
        [ 22.1],
        [ 41.4],
        [ 58.1],
        [ 39.3],
        [ 23.8],
        [ 34.3],
        [ 50.5],
        [ 70.1],
        [ 37.4],
        [ 42.3],
        [ 47.7],
        [ 29.3],


In [55]:
X.shape, y.shape

((414, 7), (414, 1))

In [8]:
np.zeros((X.shape[1], 1), dtype=float), np.zeros((1, 1))

(array([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]]),
 array([[0.]]))

In [9]:
W = np.zeros((X.shape[1], 1), dtype=float)
X.shape, W.shape

((10, 6), (6, 1))

In [90]:
def train(X, y, lr=0.1, epochs=5000):
    losses = []
    W = np.zeros((X.shape[1], 1), dtype=float)
    b = np.zeros((1, 1), dtype=float)
    for _ in range(epochs + 1):
        # y = mx + c
        pred = X @ W + b
        err = pred - y
        loss = (err ** 2).mean()
        losses.append(loss)
        W -= lr * (2/len(y)) * X.T @ err
        b -= lr * (2/len(y)) * err.mean()
        if _ % 50 == 0:
            print(f'At epoch {_}, loss = {loss}')
        

In [11]:
X.T.shape, err.shape

NameError: name 'err' is not defined

In [91]:
# normalize X along axis 0
X = (X - X.mean(axis=0)) / (X.std(axis=0) + 1e-8) # since std can be 0, to prevent divide by 0 add 1e-8
training_result = train(X, y, lr=0.361)
training_result

At epoch 0, loss = 1627.1843961352658
At epoch 50, loss = 1288.4800633854668
At epoch 100, loss = 1094.376074006067
At epoch 150, loss = 931.420957486783
At epoch 200, loss = 794.5653955180509
At epoch 250, loss = 679.6291377066648
At epoch 300, loss = 583.1015054068372
At epoch 350, loss = 502.0341035717788
At epoch 400, loss = 433.9507632503929
At epoch 450, loss = 376.77190807073816
At epoch 500, loss = 328.751034473428
At epoch 550, loss = 288.42136551095143
At epoch 600, loss = 254.55104877614647
At epoch 650, loss = 226.1055299997991
At epoch 700, loss = 202.2159530350799
At epoch 750, loss = 182.15262101992283
At epoch 800, loss = 165.30270809995338
At epoch 850, loss = 151.1515409261229
At epoch 900, loss = 139.26687817843774
At epoch 950, loss = 129.28570794059226
At epoch 1000, loss = 120.90315965698565
At epoch 1050, loss = 113.86319199261635
At epoch 1100, loss = 107.95077216053608
At epoch 1150, loss = 102.98530783778081
At epoch 1200, loss = 98.81513105047411
At epoch 125

# scikit-learn implementation

In [ ]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error

# 1. The Dataset
# data = {
#     "SqFt": [2347, 1202, 3850, 920, 1750, 2100, 3100, 1450, 2800, 1150],
#     "Age": [12, 45, 2, 80, 25, 10, 5, 30, 15, 60],
#     "Bedrooms": [4, 2, 5, 1, 3, 3, 4, 2, 4, 2],
#     "Dist_City": [3.2, 15.1, 0.8, 18.5, 7.4, 4.2, 2.1, 12.3, 5.5, 20.0],
#     "Transit": [1, 0, 1, 0, 1, 1, 1, 0, 1, 0],
#     "Luxury": [8, 3, 10, 2, 5, 7, 9, 4, 8, 1],
#     "Price_k": [485.4, 185.2, 720.5, 110.8, 315.6, 410.2, 595.3, 240.7, 510.9, 130.4]
# }

# df = pd.DataFrame(data)

# # 2. Separate Features (X) and Target (y)
# X = df.drop(columns=["Price_k"])
# y = df["Price_k"]

# 3. Feature Scaling
# Note: Standard LinearRegression mathematically doesn't *require* scaling to avoid 'nan' errors,
# but it is highly recommended so we can compare the importance of the final weights.

In [42]:
df = pd.read_csv("../Real_estate.csv")

# df.iloc[:, :-1].to_numpy()
X = df.iloc[:, :-1]
y = df.iloc[:, -1]
X, y

(      No  X1 transaction date  X2 house age  \
 0      1             2012.917          32.0   
 1      2             2012.917          19.5   
 2      3             2013.583          13.3   
 3      4             2013.500          13.3   
 4      5             2012.833           5.0   
 ..   ...                  ...           ...   
 409  410             2013.000          13.7   
 410  411             2012.667           5.6   
 411  412             2013.250          18.8   
 412  413             2013.000           8.1   
 413  414             2013.500           6.5   
 
      X3 distance to the nearest MRT station  X4 number of convenience stores  \
 0                                  84.87882                               10   
 1                                 306.59470                                9   
 2                                 561.98450                                5   
 3                                 561.98450                                5   
 4               

In [43]:

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# 4. Initialize and Train the Model
# Notice how simple this is: no epochs, no learning rate!
model = LinearRegression()
model.fit(X_scaled, y)

# 5. Make Predictions
predictions = model.predict(X_scaled)

# 6. Evaluate and View Results
mse = mean_squared_error(y, predictions)
mae = mean_absolute_error(y, predictions)



In [44]:
X

,No,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude
0,1,2012.917,32.0,84.87882,10,24.98298,121.54024
1,2,2012.917,19.5,306.59470,9,24.98034,121.53951
2,3,2013.583,13.3,561.98450,5,24.98746,121.54391
3,4,2013.500,13.3,561.98450,5,24.98746,121.54391
4,5,2012.833,5.0,390.56840,5,24.97937,121.54245
...,...,...,...,...,...,...,...
409,410,2013.000,13.7,4082.01500,0,24.94155,121.50381
410,411,2012.667,5.6,90.45606,9,24.97433,121.54310
411,412,2013.250,18.8,390.96960,7,24.97923,121.53986
412,413,2013.000,8.1,104.81010,5,24.96674,121.54067


In [45]:
y

0      37.9
1      42.2
2      47.3
3      54.8
4      43.1
       ... 
409    15.4
410    50.0
411    40.6
412    52.5
413    63.9
Name: Y house price of unit area, Length: 414, dtype: float64

In [46]:
print("--- Overall Model Performance ---")
print(f"Mean Squared Error (MSE): {mse:.2f}")
print(f"Mean Absolute Error (MAE): {mae:.2f}")

print("\n--- Final Model Parameters ---")
print(f"Bias (Intercept): {model.intercept_:.2f}")
print("Learned Weights (Coefficients):")
for feature, weight in zip(X.columns, model.coef_):
    print(f"  {feature}: {weight:.2f}")

print("\n--- Let's look at the predictions! ---")
results_df = pd.DataFrame({
    "Actual Price": y,
    "Predicted Price": np.round(predictions, 1),
    "Error": np.round(np.abs(y - predictions), 1)
})
print(results_df)

--- Overall Model Performance ---
Mean Squared Error (MSE): 76.95
Mean Absolute Error (MAE): 6.10

--- Final Model Parameters ---
Bias (Intercept): 37.98
Learned Weights (Coefficients):
  No: -0.43
  X1 transaction date: 1.43
  X2 house age: -3.08
  X3 distance to the nearest MRT station: -5.70
  X4 number of convenience stores: 3.32
  X5 latitude: 2.78
  X6 longitude: -0.22

--- Let's look at the predictions! ---
     Actual Price  Predicted Price  Error
0            37.9             47.9   10.0
1            42.2             48.6    6.4
2            47.3             49.5    2.2
3            54.8             49.1    5.7
4            43.1             46.9    3.8
..            ...              ...    ...
409          15.4             13.7    1.7
410          50.0             49.2    0.8
411          40.6             46.1    5.5
412          52.5             43.9    8.6
413          63.9             53.1   10.8

[414 rows x 3 columns]


## Sample testing

In [4]:
import numpy as np

In [11]:
X = np.array([[1, 5, 4.0], [1, 10, 4.5]])
y = np.array([20, 30]).reshape(-1, 1)
X, y

(array([[ 1. ,  5. ,  4. ],
        [ 1. , 10. ,  4.5]]),
 array([[20],
        [30]]))

In [19]:
print(X.T)
print(X)

[[ 1.   1. ]
 [ 5.  10. ]
 [ 4.   4.5]]
[[ 1.   5.   4. ]
 [ 1.  10.   4.5]]


In [17]:
np.dot(X.T, X)

array([[  2.  ,  15.  ,   8.5 ],
       [ 15.  , 125.  ,  65.  ],
       [  8.5 ,  65.  ,  36.25]])